CREATE TABLE AUTHORITIES(
    USER_NO NUMBER REFERENCES MEMBER,
    AUTHORITY VARCHAR2(15),
    PRIMARY KEY(USER_NO, AUTHORITY)
);

INSERT INTO AUTHORITIES VALUES(10, 'ROLE_ADMIN');
INSERT INTO AUTHORITIES VALUES(10, 'ROLE_USER');

COMMIT;